export const farmInfo = [
    {
        id: "01",
        type: "Banano",
        size: 4.604,
        yellow: 0.18,
        status: "Saludable",
        risk: 0.86,
    },
    {
        id: "02",
        type: "Banano",
        size: 3.205,
        yellow: 0.23,
        status: "Fusarium",
        risk: 1,
    },
    {
        id: "03",
        type: "Banano",
        size: 3.072,
        yellow: 0.18,
        status: "Saludable",
        risk: 0.86,
    },
    {
        id: "04",
        type: "Plátano",
        size: 0.506,
        yellow: 0.23,
        status: "Fusarium",
        risk: 1,
    },
    {
        id: "05",
        type: "Banano",
        size: 3.941,
        yellow: 0.18,
        status: "Saludable",
        risk: 0.86,
    },
    {
        id: "06",
        type: "Plátano",
        size: 0.473,
        yellow: 0.23,
        status: "Fusarium",
        risk: 1,
    }
]